r"""Generate a LiteLLM proxy config from the keys that actually exist.

The project's charter is surviving a rate limit without work stopping. That
requires somewhere to fail over TO, and a config listing providers you have no
key for does not start -- litellm resolves `os.environ/X` at load and refuses.
So the config is generated from the environment rather than hand-written, and
adding a provider means exporting a key, not editing YAML.

## What failover can and cannot do for you

Two different failures, and a pool only fixes one of them with one account:

| failure | one OpenRouter key | plus a second provider |
|---|---|---|
| transient overload (*"Upstream error from Nvidia"*) | **fixed** — another model, another upstream | fixed |
| per-model rate limit | **fixed** | fixed |
| free-models-per-**day** cap | **not fixed** — the cap is account-wide | fixed |

Saying a pool fixes the daily cap would be the comfortable answer and the
wrong one: OpenRouter counts free requests per account, not per model. The
`:free` models below buy resilience against the first two rows, which is what
actually interrupted a real run, and nothing against the third.

## Fallbacks are ordered, and the order is a cost decision

`fallbacks` sends the next attempt to the next entry. Free models come first
and paid providers last, so an outage degrades toward *slower*, never silently
toward *billed*. `docs/0002` §5: never silently spend.
"""
from __future__ import annotations

import os
from pathlib import Path

# (env var, litellm model, short name, is_free). Order is fallback order:
# free first, paid last, so degrading never silently costs money.
CANDIDATES: list[tuple[str, str, str, bool]] = [
    ("OPENROUTER_API_KEY", "openrouter/nex-agi/nex-n2.5-pro:free",
     "or-nex", True),
    ("OPENROUTER_API_KEY", "openrouter/nvidia/nemotron-3-super-120b-a12b:free",
     "or-nemotron", True),
    ("OPENROUTER_API_KEY", "openrouter/deepseek/deepseek-chat-v3.1:free",
     "or-deepseek", True),
    ("GEMINI_API_KEY", "gemini/gemini-2.5-flash", "gemini-flash", True),
    ("MISTRAL_API_KEY", "mistral/mistral-small-latest", "mistral-small", True),
    ("CEREBRAS_API_KEY", "cerebras/llama-3.3-70b", "cerebras-llama", True),
    ("GROQ_API_KEY", "groq/llama-3.3-70b-versatile", "groq-llama", True),
    ("ANTHROPIC_API_KEY", "anthropic/claude-sonnet-5", "anthropic-sonnet", False),
    ("OPENAI_API_KEY", "openai/gpt-4o-mini", "openai-mini", False),
]

POOL = "pool"


def available(env: dict | None = None) -> list[tuple[str, str, str, bool]]:
    """Candidates whose key is actually set."""
    e = env if env is not None else os.environ
    return [c for c in CANDIDATES if e.get(c[0])]


def accounts(entries: list[tuple[str, str, str, bool]]) -> set[str]:
    """Distinct credentials behind the pool.

    The number that matters. Three models on one key is one account, and an
    account-wide daily cap takes all three down together.
    """
    return {c[0] for c in entries}


def build(env: dict | None = None, telemetry: str | Path | None = None) -> str:
    """The proxy config, as YAML text."""
    entries = available(env)
    if not entries:
        raise SystemExit(
            "no provider keys in the environment — nothing to route to.\n"
            "  set at least one, e.g. OPENROUTER_API_KEY")

    lines = [
        "# GENERATED by `agentctl proxy` from the keys in your environment.",
        "# Re-run it after exporting a new provider key; do not hand-edit.",
        "#",
        f"# {len(entries)} deployment(s) across {len(accounts(entries))} "
        f"account(s).",
        "",
        "model_list:",
    ]
    for env_var, model, short, is_free in entries:
        lines += [
            f"  - model_name: {POOL}",
            "    litellm_params:",
            f"      model: {model}",
            f"      api_key: os.environ/{env_var}",
            "    model_info:",
            f"      id: {short}",
            f"      free: {str(is_free).lower()}",
        ]

    # Same order as model_list: free first, paid last.
    order = ", ".join(f'"{c[2]}"' for c in entries[1:])
    lines += [
        "",
        "litellm_settings:",
        "  # Seam A. Cost attribution and turn affinity; it cannot block a",
        "  # request (`docs/0021`).",
        "  callbacks: agentctl_hook.proxy_handler_instance",
        "  drop_params: true",
        "",
        "router_settings:",
        "  routing_strategy: simple-shuffle",
        "  num_retries: 2",
        "  allowed_fails: 1",
        "  cooldown_time: 60",
    ]
    if len(entries) > 1:
        lines += [
            "  # Degrade toward slower, never silently toward billed.",
            f"  fallbacks: [{{\"{POOL}\": [{order}]}}]"
            if order else "",
        ]
    lines.append("")
    text = "\n".join(l for l in lines if l is not None)

    # Parse our own output before handing it over. The first version of this
    # function emitted `["a" "b"]` -- a missing comma -- and returned it
    # happily; the proxy would have failed to start with a YAML error pointing
    # at a file the user never wrote. A generator that cannot detect its own
    # malformed output is the same shape as a guard that cannot fail
    # (`docs/0028` §5).
    _validate(text)
    return text


def _validate(text: str) -> None:
    import yaml

    try:
        doc = yaml.safe_load(text)
    except yaml.YAMLError as e:
        raise AssertionError(f"generated an invalid proxy config: {e}") from e

    assert isinstance(doc, dict), "config is not a mapping"
    models = doc.get("model_list") or []
    assert models, "config has no model_list"
    names = {m["model_name"] for m in models}
    # One name is what makes them a POOL rather than separate models.
    assert names == {POOL}, f"deployments must share one model_name, got {names}"
    for m in models:
        assert m["litellm_params"].get("api_key", "").startswith("os.environ/"), \
            "a key was inlined instead of referenced from the environment"
    fb = (doc.get("router_settings") or {}).get("fallbacks")
    if fb:
        assert isinstance(fb, list) and isinstance(fb[0], dict), \
            f"fallbacks is malformed: {fb!r}"


HOOK_MODULE = '''"""Seam A for the proxy. Loaded by `litellm_settings.callbacks`.

Generated by `agentctl proxy`. The hook records cost telemetry and stamps turn
affinity; it never blocks a request -- effects are gated at Seams B and C
inside the agent, not here (`docs/0008` §3).
"""
import os

from agentctl.adapters.litellm.hook import AgentctlHook

proxy_handler_instance = AgentctlHook(
    telemetry_path=os.environ.get("AGENTCTL_TELEMETRY", "hook_telemetry.json"))
'''


def write(out_dir: str | Path = ".", env: dict | None = None) -> tuple[Path, Path]:
    d = Path(out_dir)
    d.mkdir(parents=True, exist_ok=True)
    cfg = d / "proxy_config.yaml"
    hook = d / "agentctl_hook.py"
    cfg.write_text(build(env), encoding="utf-8")
    hook.write_text(HOOK_MODULE, encoding="utf-8")
    return cfg, hook
